blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/rishii-hub/realtime-lane-detection/discussions
    about: Ask questions and share ideas with the community.
